// @generated by tsquid-codegen. Do not edit.
import { createURI } from "../runtime/uri";
import { createRouteContextRegistry, type RouteContextValue } from "../runtime/context";

export enum RouteName {
  Tutorials = "Tutorials",
  TutorialDetail = "TutorialDetail",
  Playlists = "Playlists",
}

export type TutorialsInputType = {
  filter?: string;
};
export const TutorialsURI = createURI<TutorialsInputType>("/tutorials", {"filter":{"kind":"string","optional":true}});


export type TutorialDetailInputType = {
  id: string;
};
export const TutorialDetailURI = createURI<TutorialDetailInputType>("/tutorials/:id", {"id":{"kind":"string","optional":false}});


export type PlaylistsInputType = {
};
export const PlaylistsURI = createURI<PlaylistsInputType>("/playlists", {});


export type RouteContextType =
  RouteContextValue<TutorialsInputType, RouteName.Tutorials>
  | RouteContextValue<TutorialDetailInputType, RouteName.TutorialDetail>
  | RouteContextValue<PlaylistsInputType, RouteName.Playlists>;

const ROUTE_CONTEXT = createRouteContextRegistry<RouteContextType>();
export const TutorialsRouteContext = ROUTE_CONTEXT.forRoute(RouteName.Tutorials);
export const TutorialDetailRouteContext = ROUTE_CONTEXT.forRoute(RouteName.TutorialDetail);
export const PlaylistsRouteContext = ROUTE_CONTEXT.forRoute(RouteName.Playlists);

export type PlaylistRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.Playlists }>;
export function usePlaylistRouteContext(): PlaylistRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.Playlists:
      return context;
    default:
      throw new Error('usePlaylistRouteContext requires the Playlist entrypoint; current route is ' + currentRoute);
  }
}

export type TutorialRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.Tutorials | RouteName.TutorialDetail }>;
export function useTutorialRouteContext(): TutorialRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.Tutorials:
    case RouteName.TutorialDetail:
      return context;
    default:
      throw new Error('useTutorialRouteContext requires the Tutorial entrypoint; current route is ' + currentRoute);
  }
}
