use serde::Deserialize;
use std::{collections::BTreeMap, env, fs, path::Path};

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Config {
    runtime: String,
    routes: Vec<Route>,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Route {
    name: String,
    #[serde(rename = "entryPoint")]
    entry_point: String,
    path: String,
    fields: BTreeMap<String, Field>,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Field {
    kind: String,
    #[serde(default)]
    optional: bool,
}

fn identifier(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .enumerate()
            .all(|(i, c)| c.is_ascii_alphabetic() || c == '_' || (i > 0 && c.is_ascii_digit()))
}
fn generate(config: &Config) -> Result<String, String> {
    let mut out = format!("// @generated by tsquid-codegen. Do not edit.\nimport {{ createURI }} from {};\nimport {{ createRouteContextRegistry, type RouteContextValue }} from {};\n", serde_json::to_string(&format!("{}/uri",config.runtime)).unwrap(), serde_json::to_string(&format!("{}/context",config.runtime)).unwrap());
    let mut names = std::collections::BTreeSet::new();
    let mut paths = std::collections::BTreeSet::new();
    let mut entry_points: BTreeMap<&str, Vec<&str>> = BTreeMap::new();
    let mut modules = BTreeMap::new();
    out += "\nexport enum RouteName {\n";
    for route in &config.routes {
        if !identifier(&route.name)
            || ["__proto__", "constructor", "prototype"].contains(&route.name.as_str())
        {
            return Err("Invalid route name".into());
        }
        let module = route.entry_point.as_str();
        let entry_point = Path::new(module)
            .file_name()
            .and_then(|s| s.to_str())
            .and_then(|s| s.strip_suffix(".entrypoint.ts"))
            .filter(|s| identifier(s))
            .ok_or("Entrypoint modules must be named <Name>.entrypoint.ts")?;
        if module.contains('\\')
            || Path::new(module).is_absolute()
            || module
                .split('/')
                .any(|part| part.is_empty() || part == "." || part == "..")
        {
            return Err(
                "Entrypoint module paths must be normalized paths relative to the config".into(),
            );
        }
        if let Some(previous) = modules.insert(entry_point, module) {
            if previous != module {
                return Err(format!("Entrypoint module name {entry_point} is ambiguous"));
            }
        }
        entry_points
            .entry(entry_point)
            .or_default()
            .push(&route.name);
        out += &format!(
            "  {} = {},\n",
            route.name,
            serde_json::to_string(&route.name).unwrap()
        );
    }
    out += "}\n";
    for route in &config.routes {
        if !identifier(&route.name) || !names.insert(&route.name) {
            return Err("Invalid or duplicate route name".into());
        }
        if !route.path.starts_with('/')
            || route.path.contains(['?', '#', '*', '\\'])
            || route.path.contains("//")
            || route.path.split('/').any(|part| {
                part == "." || part == ".." || (!part.starts_with(':') && part.contains(':'))
            })
            || !paths.insert(&route.path)
        {
            return Err("Invalid or duplicate route path".into());
        }
        let mut params = std::collections::BTreeSet::new();
        for part in route.path.split('/').filter(|s| s.starts_with(':')) {
            let key = &part[1..];
            let field = route
                .fields
                .get(key)
                .ok_or(format!("Missing path field {key}"))?;
            if field.optional || field.kind.ends_with("[]") || !params.insert(key) {
                return Err(format!("Invalid path field {key}"));
            }
        }
        out += &format!("\nexport type {}InputType = {{\n", route.name);
        for (key, field) in &route.fields {
            if !identifier(key) || ["__proto__", "constructor", "prototype"].contains(&key.as_str())
            {
                return Err(format!("Invalid field {key}"));
            }
            let (base, array) = field
                .kind
                .strip_suffix("[]")
                .map_or((field.kind.as_str(), false), |s| (s, true));
            let ts = match base {
                "string" => "string",
                "int" => "number",
                "bool" => "boolean",
                _ => return Err(format!("Unsupported kind {}", field.kind)),
            };
            out += &format!(
                "  {key}{}: {ts}{};\n",
                if field.optional { "?" } else { "" },
                if array { "[]" } else { "" }
            );
        }
        out += "};\n";
        let fields: BTreeMap<_, _> = route
            .fields
            .iter()
            .map(|(k, v)| (k, serde_json::json!({"kind":v.kind,"optional":v.optional})))
            .collect();
        out += &format!(
            "export const {}URI = createURI<{}InputType>({}, {});\n\n",
            route.name,
            route.name,
            serde_json::to_string(&route.path).unwrap(),
            serde_json::to_string(&fields).unwrap()
        );
    }
    out += "\nexport type RouteContextType =\n";
    if config.routes.is_empty() {
        out += "  never;\n";
    } else {
        for (index, route) in config.routes.iter().enumerate() {
            out += &format!(
                "  {}RouteContextValue<{}InputType, RouteName.{}>{}\n",
                if index == 0 { "" } else { "| " },
                route.name,
                route.name,
                if index + 1 == config.routes.len() {
                    ";"
                } else {
                    ""
                }
            );
        }
    }
    out += "\nconst ROUTE_CONTEXT = createRouteContextRegistry<RouteContextType>();\n";
    for route in &config.routes {
        out += &format!(
            "export const {}RouteContext = ROUTE_CONTEXT.forRoute(RouteName.{});\n",
            route.name, route.name
        );
    }
    for (entry_point, routes) in entry_points {
        let route_names = routes
            .iter()
            .map(|name| format!("RouteName.{name}"))
            .collect::<Vec<_>>()
            .join(" | ");
        out += &format!("\nexport type {entry_point}RouteContextType = Extract<RouteContextType, {{ currentRoute: {route_names} }}>;\nexport function use{entry_point}RouteContext(): {entry_point}RouteContextType {{\n  const context = ROUTE_CONTEXT.useRouteContext();\n  const currentRoute = context.currentRoute;\n  switch (context.currentRoute) {{\n");
        for route in routes {
            out += &format!("    case RouteName.{route}:\n");
        }
        out += &format!("      return context;\n    default:\n      throw new Error('use{entry_point}RouteContext requires the {entry_point} entrypoint; current route is ' + currentRoute);\n  }}\n}}\n");
    }
    Ok(out)
}
fn run() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<_> = env::args().skip(1).collect();
    if args.len() < 2 || args.len() > 3 || (args.len() == 3 && args[2] != "--check") {
        return Err("Usage: tsquid-codegen CONFIG.json OUTPUT.ts [--check]".into());
    }
    let config: Config = serde_json::from_str(&fs::read_to_string(&args[0])?)?;
    let output = generate(&config)?;
    if args.len() == 3 {
        if fs::read_to_string(&args[1]).ok().as_deref() != Some(&output) {
            return Err("Generated routes are stale; regenerate them".into());
        }
    } else {
        if let Some(parent) = Path::new(&args[1])
            .parent()
            .filter(|p| !p.as_os_str().is_empty())
        {
            fs::create_dir_all(parent)?;
        }
        fs::write(&args[1], output)?;
    }
    Ok(())
}
fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn config(path: &str, fields: &str) -> Config {
        serde_json::from_str(&format!(r#"{{"runtime":"./runtime","routes":[{{"name":"Tutorial","entryPoint":"Tutorial.entrypoint.ts","path":"{path}","fields":{fields}}}]}}"#)).unwrap()
    }
    #[test]
    fn generates_types() {
        let text = generate(&config(
            "/tutorials/:id",
            r#"{"id":{"kind":"int"},"tags":{"kind":"string[]","optional":true}}"#,
        ))
        .unwrap();
        assert!(text.contains("id: number"));
        assert!(text.contains("tags?: string[]"));
        assert!(text.contains("TutorialRouteContext"));
    }
    #[test]
    fn rejects_bad_schemas() {
        for (path, fields) in [
            ("/x/:id", "{}"),
            ("/x/:id", r#"{"id":{"kind":"int","optional":true}}"#),
            ("/x", r#"{"id":{"kind":"object"}}"#),
            ("/x/:id", r#"{"id":{"kind":"int[]"}}"#),
        ] {
            assert!(generate(&config(path, fields)).is_err());
        }
    }
    #[test]
    fn generated_fixture_is_current() {
        let config: Config = serde_json::from_str(include_str!("../../../packages/routes/tests/routes.json")).unwrap();
        assert_eq!(
            generate(&config).unwrap(),
            include_str!("../../../packages/routes/tests/routes.generated.ts")
        );
    }

    #[test]
    fn derives_hooks_from_entrypoint_module_names() {
        let config: Config = serde_json::from_str(include_str!("../../../packages/routes/tests/routes.json")).unwrap();
        let text = generate(&config).unwrap();
        assert!(text.contains("export enum RouteName"));
        assert_eq!(
            text.matches("export function useTutorialRouteContext()")
                .count(),
            1
        );
        assert!(text.contains("currentRoute: RouteName.Tutorials | RouteName.TutorialDetail"));
        assert!(text.contains("export function usePlaylistRouteContext()"));
    }

    #[test]
    fn rejects_invalid_or_ambiguous_module_names() {
        for module in [
            "Tutorial",
            "Tutorial.ts",
            "Tutorial.entrypoint.tsx",
            "bad-name.entrypoint.ts",
            "/Tutorial.entrypoint.ts",
            "../Tutorial.entrypoint.ts",
        ] {
            let mut config = config("/tutorials", "{}");
            config.routes[0].entry_point = module.into();
            assert!(generate(&config).is_err(), "{module}");
        }
        let mut config: Config =
            serde_json::from_str(include_str!("../../../packages/routes/tests/routes.json")).unwrap();
        config.routes[1].entry_point = "other/Tutorial.entrypoint.ts".into();
        assert!(generate(&config).unwrap_err().contains("ambiguous"));
    }
}
