// @generated by tsquid-codegen. Do not edit.
import { createURI } from "@tsquid/routes/uri";
import { createRouteContextRegistry, type RouteContextValue } from "@tsquid/routes/context";

export enum RouteName {
  Home = "Home",
  Profile = "Profile",
}

export type HomeInputType = {
};
export const HomeURI = createURI<HomeInputType>("/", {});


export type ProfileInputType = {
};
export const ProfileURI = createURI<ProfileInputType>("/me", {});


export type RouteContextType =
  RouteContextValue<HomeInputType, RouteName.Home>
  | RouteContextValue<ProfileInputType, RouteName.Profile>;

const ROUTE_CONTEXT = createRouteContextRegistry<RouteContextType>();
export const HomeRouteContext = ROUTE_CONTEXT.forRoute(RouteName.Home);
export const ProfileRouteContext = ROUTE_CONTEXT.forRoute(RouteName.Profile);

export type HomeRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.Home }>;
export function useHomeRouteContext(): HomeRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.Home:
      return context;
    default:
      throw new Error('useHomeRouteContext requires the Home entrypoint; current route is ' + currentRoute);
  }
}

export type ProfileRouteContextType = Extract<RouteContextType, { currentRoute: RouteName.Profile }>;
export function useProfileRouteContext(): ProfileRouteContextType {
  const context = ROUTE_CONTEXT.useRouteContext();
  const currentRoute = context.currentRoute;
  switch (context.currentRoute) {
    case RouteName.Profile:
      return context;
    default:
      throw new Error('useProfileRouteContext requires the Profile entrypoint; current route is ' + currentRoute);
  }
}
