use serde::Deserialize;
use std::{collections::BTreeMap, env, fs, path::Path};

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Config {
    runtime: String,
    routes: Vec<Route>,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Route {
    name: String,
    path: String,
    fields: BTreeMap<String, Field>,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Field {
    kind: String,
    #[serde(default)]
    optional: bool,
}

fn identifier(s: &str) -> bool {
    !s.is_empty()
        && s.chars()
            .enumerate()
            .all(|(i, c)| c.is_ascii_alphabetic() || c == '_' || (i > 0 && c.is_ascii_digit()))
}
fn generate(config: &Config) -> Result<String, String> {
    let mut out = format!("// @generated by tsquid-codegen. Do not edit.\nimport {{ createURI }} from {};\nimport {{ createRouteContext }} from {};\n", serde_json::to_string(&format!("{}/uri",config.runtime)).unwrap(), serde_json::to_string(&format!("{}/context",config.runtime)).unwrap());
    let mut names = std::collections::BTreeSet::new();
    let mut paths = std::collections::BTreeSet::new();
    for route in &config.routes {
        if !identifier(&route.name) || !names.insert(&route.name) {
            return Err("Invalid or duplicate route name".into());
        }
        if !route.path.starts_with('/')
            || route.path.contains(['?', '#', '*', '\\'])
            || route.path.contains("//")
            || route.path.split('/').any(|part| {
                part == "." || part == ".." || (!part.starts_with(':') && part.contains(':'))
            })
            || !paths.insert(&route.path)
        {
            return Err("Invalid or duplicate route path".into());
        }
        let mut params = std::collections::BTreeSet::new();
        for part in route.path.split('/').filter(|s| s.starts_with(':')) {
            let key = &part[1..];
            let field = route
                .fields
                .get(key)
                .ok_or(format!("Missing path field {key}"))?;
            if field.optional || field.kind.ends_with("[]") || !params.insert(key) {
                return Err(format!("Invalid path field {key}"));
            }
        }
        out += &format!("\nexport type {}InputType = {{\n", route.name);
        for (key, field) in &route.fields {
            if !identifier(key) || ["__proto__", "constructor", "prototype"].contains(&key.as_str())
            {
                return Err(format!("Invalid field {key}"));
            }
            let (base, array) = field
                .kind
                .strip_suffix("[]")
                .map_or((field.kind.as_str(), false), |s| (s, true));
            let ts = match base {
                "string" => "string",
                "int" => "number",
                "bool" => "boolean",
                _ => return Err(format!("Unsupported kind {}", field.kind)),
            };
            out += &format!(
                "  {key}{}: {ts}{};\n",
                if field.optional { "?" } else { "" },
                if array { "[]" } else { "" }
            );
        }
        out += "};\n";
        let fields: BTreeMap<_, _> = route
            .fields
            .iter()
            .map(|(k, v)| (k, serde_json::json!({"kind":v.kind,"optional":v.optional})))
            .collect();
        out += &format!("export const {}URI = createURI<{}InputType>({}, {});\nexport const {}RouteContext = createRouteContext<{}InputType>();\n", route.name, route.name, serde_json::to_string(&route.path).unwrap(), serde_json::to_string(&fields).unwrap(), route.name, route.name);
    }
    Ok(out)
}
fn run() -> Result<(), Box<dyn std::error::Error>> {
    let args: Vec<_> = env::args().skip(1).collect();
    if args.len() < 2 || args.len() > 3 || (args.len() == 3 && args[2] != "--check") {
        return Err("Usage: tsquid-codegen CONFIG.json OUTPUT.ts [--check]".into());
    }
    let config: Config = serde_json::from_str(&fs::read_to_string(&args[0])?)?;
    let output = generate(&config)?;
    if args.len() == 3 {
        if fs::read_to_string(&args[1]).ok().as_deref() != Some(&output) {
            return Err("Generated routes are stale; regenerate them".into());
        }
    } else {
        if let Some(parent) = Path::new(&args[1])
            .parent()
            .filter(|p| !p.as_os_str().is_empty())
        {
            fs::create_dir_all(parent)?;
        }
        fs::write(&args[1], output)?;
    }
    Ok(())
}
fn main() {
    if let Err(error) = run() {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    fn config(path: &str, fields: &str) -> Config {
        serde_json::from_str(&format!(r#"{{"runtime":"./runtime","routes":[{{"name":"Tutorial","path":"{path}","fields":{fields}}}]}}"#)).unwrap()
    }
    #[test]
    fn generates_types() {
        let text = generate(&config(
            "/tutorials/:id",
            r#"{"id":{"kind":"int"},"tags":{"kind":"string[]","optional":true}}"#,
        ))
        .unwrap();
        assert!(text.contains("id: number"));
        assert!(text.contains("tags?: string[]"));
        assert!(text.contains("TutorialRouteContext"));
    }
    #[test]
    fn rejects_bad_schemas() {
        for (path, fields) in [
            ("/x/:id", "{}"),
            ("/x/:id", r#"{"id":{"kind":"int","optional":true}}"#),
            ("/x", r#"{"id":{"kind":"object"}}"#),
            ("/x/:id", r#"{"id":{"kind":"int[]"}}"#),
        ] {
            assert!(generate(&config(path, fields)).is_err());
        }
    }
}
